server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: gateway
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG

common:
  front: http://localhost:3000,https://sgiufape.vercel.app,https://lmtsteste20.ufape.edu.br
spring:
  application:
    name: sgu-gateway-service
  profiles:
    active: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/sgu-ufape/protocol/openid-connect/certs
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: sgu-auth-service
              uri: lb://sgu-auth-service
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
            - id: sgu-prae-service
              uri: lb://sgu-prae-service
              predicates:
                - Path=/prae/**
              filters:
                - StripPrefix=1
            - id: sgu-pdi-service
              uri: lb://sgu-pdi-service
              predicates:
                - Path=/pdi/**
              filters:
                - StripPrefix=1
            - id: sgu-editais-service
              uri: lb://sgu-editais-service
              predicates:
                - Path=/editais/**
              filters:
                - StripPrefix=1
            - id: sgu-extra-sisu-service
              uri: lb://sgu-extra-sisu-service
              predicates:
                - Path=/extra-sisu/**
              filters:
                - StripPrefix=1
                - AddRequestHeader=X-Forwarded-Prefix, /extra-sisu

---
spring:
  config:
    activate:
      on-profile: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/sgu-ufape/protocol/openid-connect/certs

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: gateway
    prefer-ip-address: false


